#!/usr/bin/env node
// Downloads the self-hosted, latin-subset woff2 files for TypeJung's three
// typefaces and emits public/fonts/fonts.css. Keeping only the latin and
// latin-ext subsets (dropping vietnamese/greek/cyrillic) is the real payload
// cut versus loading the full Google Fonts variable files at runtime.
//
// Re-run with: node scripts/fetch-fonts.mjs

import { mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, '..', 'public', 'fonts');
mkdirSync(outDir, { recursive: true });

// A modern desktop UA is required so the CSS API serves woff2 (not ttf).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Subsets we keep. Everything else (vietnamese, greek, cyrillic, …) is dropped.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const families = [
  {
    key: 'fraunces',
    css: 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..700&display=swap',
  },
  {
    key: 'fraunces-italic',
    css: 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@1,9..144,400..700&display=swap',
  },
  {
    key: 'schibsted',
    css: 'https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@400..700&display=swap',
  },
  {
    key: 'spline-mono',
    css: 'https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@400..600&display=swap',
  },
];

const fetchText = async (url) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return res.text();
};

const fetchBinary = async (url) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
};

// Split a Google Fonts stylesheet into { subsetComment, block } pairs.
const parseFaces = (css) => {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*{[^}]*})/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    faces.push({ subset: match[1], block: match[2] });
  }
  return faces;
};

let cssOut = '/* Self-hosted, latin-subset fonts. Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n';
let downloaded = 0;

for (const family of families) {
  const css = await fetchText(family.css);
  const faces = parseFaces(css);
  let index = 0;

  for (const { subset, block } of faces) {
    if (!KEEP_SUBSETS.has(subset)) continue;

    const urlMatch = block.match(/src:\s*url\(([^)]+)\)/);
    if (!urlMatch) continue;
    const woffUrl = urlMatch[1];

    const fileName = `${family.key}-${subset}-${index}.woff2`;
    const buffer = await fetchBinary(woffUrl);
    writeFileSync(join(outDir, fileName), buffer);
    downloaded += 1;
    index += 1;

    const localBlock = block.replace(
      /src:\s*url\([^)]+\)\s*format\(([^)]+)\)/,
      `src: url(/fonts/${fileName}) format($1)`,
    );
    cssOut += `/* ${family.key} ${subset} */\n${localBlock}\n\n`;
    console.log(`Saved ${fileName} (${(buffer.length / 1024).toFixed(1)} KB)`);
  }
}

writeFileSync(join(outDir, 'fonts.css'), cssOut);
console.log(`\nWrote public/fonts/fonts.css with ${downloaded} woff2 files.`);
