// Comprehensive SEO data for all pages

export const functionData = {
  ni: {
    code: 'Ni',
    name: 'Introverted Intuition',
    nickname: 'The Pattern Seer',
    description: 'Synthesizes information into unified visions and insights. Operates unconsciously, delivering "aha" moments with deep conviction.',
    dominantTypes: ['INFJ', 'INTJ'],
    auxiliaryTypes: ['ENFJ', 'ENTJ'],
    keywords: ['pattern recognition', 'future vision', 'unconscious insight', 'convergent thinking', 'symbolic understanding'],
    characteristics: [
      'Sees patterns beneath the surface that others miss',
      'Experiences sudden insights and "knowing" without conscious reasoning',
      'Focused on a single, unified vision of how things will unfold',
      'Trusts gut feelings and hunches that prove accurate over time',
      'Thinks in symbols, metaphors, and abstract patterns',
      'Often described as "prophetic" or having strong intuition',
    ],
    strengths: ['Strategic foresight', 'Pattern synthesis', 'Long-term planning', 'Insight generation'],
    challenges: ['Difficulty explaining intuitions', 'May seem disconnected from present', 'Can be seen as mysterious'],
  },
  ne: {
    code: 'Ne',
    name: 'Extraverted Intuition',
    nickname: 'The Possibility Explorer',
    description: 'Explores possibilities and connections in the external world. Generates ideas rapidly, seeing multiple angles simultaneously.',
    dominantTypes: ['ENFP', 'ENTP'],
    auxiliaryTypes: ['INFP', 'INTP'],
    keywords: ['brainstorming', 'possibilities', 'connections', 'novelty', 'divergent thinking'],
    characteristics: [
      'Generates multiple ideas and possibilities rapidly',
      'Sees connections between seemingly unrelated concepts',
      'Energized by brainstorming and exploring "what if" scenarios',
      'Constantly scanning the environment for new opportunities',
      'Enjoys novelty and gets bored with routine',
      'Natural at seeing things from multiple perspectives simultaneously',
    ],
    strengths: ['Idea generation', 'Adaptability', 'Innovation', 'Seeing potential'],
    challenges: ['May struggle with follow-through', 'Can be scattered', 'Difficulty choosing one path'],
  },
  si: {
    code: 'Si',
    name: 'Introverted Sensing',
    nickname: 'The Detail Keeper',
    description: 'Stores and recalls detailed sensory impressions from past experiences. Creates a rich internal library of "how things are."',
    dominantTypes: ['ISFJ', 'ISTJ'],
    auxiliaryTypes: ['ESFJ', 'ESTJ'],
    keywords: ['memory', 'tradition', 'detail', 'consistency', 'past experience'],
    characteristics: [
      'Has detailed, vivid memories of past experiences',
      'Compares present situations to past experiences for guidance',
      'Values tradition, consistency, and proven methods',
      'Notices when things are different from how they "should" be',
      'Builds expertise through repeated experience and practice',
      'Creates and maintains reliable systems and routines',
    ],
    strengths: ['Attention to detail', 'Reliability', 'Institutional memory', 'Quality assurance'],
    challenges: ['May resist change', 'Can be overly focused on the past', 'May miss new possibilities'],
  },
  se: {
    code: 'Se',
    name: 'Extraverted Sensing',
    nickname: 'The Present Moment Master',
    description: 'Engages directly with the present moment through the five senses. Attuned to aesthetics, physical environment, and immediate opportunities.',
    dominantTypes: ['ESFP', 'ESTP'],
    auxiliaryTypes: ['ISFP', 'ISTP'],
    keywords: ['present moment', 'sensory experience', 'action', 'aesthetics', 'physical awareness'],
    characteristics: [
      'Fully present and engaged with the immediate environment',
      'Highly attuned to sensory details—sights, sounds, textures, tastes',
      'Quick to notice and respond to changes in the environment',
      'Energized by action and physical experiences',
      'Natural sense of aesthetics and style',
      'Thrives in high-stimulus, fast-paced situations',
    ],
    strengths: ['Quick reflexes', 'Aesthetic sense', 'Crisis response', 'Physical awareness'],
    challenges: ['May struggle with long-term planning', 'Can be impulsive', 'May overlook abstract implications'],
  },
  ti: {
    code: 'Ti',
    name: 'Introverted Thinking',
    nickname: 'The Logic Architect',
    description: 'Builds precise internal logical frameworks. Seeks to understand how things work at a fundamental level.',
    dominantTypes: ['INTP', 'ISTP'],
    auxiliaryTypes: ['ENTP', 'ESTP'],
    keywords: ['logic', 'analysis', 'frameworks', 'precision', 'understanding'],
    characteristics: [
      'Builds comprehensive internal models of how systems work',
      'Values logical consistency and precision above all',
      'Constantly refining understanding and categorizations',
      'Questions assumptions and seeks root causes',
      'Prefers understanding principles over following procedures',
      'Independent thinker who trusts internal analysis',
    ],
    strengths: ['Analytical depth', 'Problem-solving', 'System understanding', 'Logical precision'],
    challenges: ['May seem detached', 'Can over-analyze', 'May struggle communicating complex ideas'],
  },
  te: {
    code: 'Te',
    name: 'Extraverted Thinking',
    nickname: 'The Efficiency Expert',
    description: 'Organizes the external world for efficiency and results. Values measurable outcomes, clear processes, and getting things done.',
    dominantTypes: ['ENTJ', 'ESTJ'],
    auxiliaryTypes: ['INTJ', 'ISTJ'],
    keywords: ['efficiency', 'organization', 'results', 'systems', 'leadership'],
    characteristics: [
      'Naturally organizes people, processes, and resources for efficiency',
      'Focuses on measurable results and objective criteria',
      'Creates clear systems, procedures, and hierarchies',
      'Makes decisions based on logic and external evidence',
      'Drives toward goals with determination and directness',
      'Natural at delegation and project management',
    ],
    strengths: ['Organization', 'Leadership', 'Goal achievement', 'Systematic thinking'],
    challenges: ['May overlook feelings', 'Can be seen as controlling', 'May dismiss subjective factors'],
  },
  fi: {
    code: 'Fi',
    name: 'Introverted Feeling',
    nickname: 'The Values Guardian',
    description: 'Evaluates everything against a deep internal value system. Attuned to authenticity, personal meaning, and emotional integrity.',
    dominantTypes: ['INFP', 'ISFP'],
    auxiliaryTypes: ['ENFP', 'ESFP'],
    keywords: ['values', 'authenticity', 'meaning', 'integrity', 'personal ethics'],
    characteristics: [
      'Has a deeply personal, nuanced internal value system',
      'Immediately senses when something violates personal values',
      'Seeks authenticity in self and others',
      'Processes emotions internally and privately',
      'Strong sense of personal identity and integrity',
      'Advocates for causes aligned with deep values',
    ],
    strengths: ['Authenticity', 'Moral clarity', 'Empathy', 'Personal integrity'],
    challenges: ['May struggle expressing feelings', 'Can be seen as stubborn', 'May take criticism personally'],
  },
  fe: {
    code: 'Fe',
    name: 'Extraverted Feeling',
    nickname: 'The Harmony Weaver',
    description: 'Focused on social harmony and group dynamics. Reads and responds to the emotional atmosphere and meets others\' emotional needs.',
    dominantTypes: ['ENFJ', 'ESFJ'],
    auxiliaryTypes: ['INFJ', 'ISFJ'],
    keywords: ['harmony', 'connection', 'social dynamics', 'emotional atmosphere', 'group needs'],
    characteristics: [
      'Naturally reads and responds to the emotional atmosphere of groups',
      'Prioritizes maintaining harmony and positive relationships',
      'Skilled at meeting others\' emotional needs',
      'Values social norms and appropriate behavior',
      'Creates connection and brings people together',
      'Expresses emotions openly and encourages others to share',
    ],
    strengths: ['Social intelligence', 'Diplomacy', 'Team building', 'Emotional support'],
    challenges: ['May neglect own needs', 'Can be people-pleasing', 'May avoid necessary conflict'],
  },
};

export const typeData = {
  intj: {
    code: 'INTJ',
    name: 'The Architect',
    stack: 'Ni-Te-Fi-Se',
    description: 'Strategic visionaries who see the world as a chess board. They combine long-term vision with systematic execution to build complex systems and achieve ambitious goals.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ni', description: 'Introverted Intuition provides strategic vision and pattern recognition' },
      { position: 'Auxiliary', function: 'Te', description: 'Extraverted Thinking executes plans with efficiency and logic' },
      { position: 'Tertiary', function: 'Fi', description: 'Introverted Feeling guides personal values and authenticity' },
      { position: 'Inferior', function: 'Se', description: 'Extraverted Sensing connects to present-moment experience' },
    ],
    keywords: ['strategic', 'independent', 'analytical', 'determined', 'innovative'],
    strengths: ['Strategic planning', 'Systems thinking', 'Independence', 'High standards', 'Innovation'],
    challenges: ['Impatience with inefficiency', 'May seem cold or arrogant', 'Perfectionism', 'Difficulty with small talk'],
    famousExamples: ['Elon Musk', 'Isaac Newton', 'Nikola Tesla', 'Michelle Obama'],
    careers: ['Engineer', 'Scientist', 'Strategist', 'Architect', 'Executive', 'Professor'],
  },
  intp: {
    code: 'INTP',
    name: 'The Logician',
    stack: 'Ti-Ne-Si-Fe',
    description: 'Analytical problem-solvers who love exploring theoretical frameworks. They seek to understand how things work at the deepest level.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ti', description: 'Introverted Thinking builds precise logical frameworks' },
      { position: 'Auxiliary', function: 'Ne', description: 'Extraverted Intuition explores possibilities and connections' },
      { position: 'Tertiary', function: 'Si', description: 'Introverted Sensing provides memory and attention to detail' },
      { position: 'Inferior', function: 'Fe', description: 'Extraverted Feeling navigates social harmony' },
    ],
    keywords: ['analytical', 'curious', 'logical', 'inventive', 'independent'],
    strengths: ['Logical analysis', 'Innovation', 'Problem-solving', 'Abstract thinking', 'Objectivity'],
    challenges: ['Social situations', 'Emotional expression', 'Following through', 'Practical details'],
    famousExamples: ['Albert Einstein', 'Bill Gates', 'Marie Curie', 'Charles Darwin'],
    careers: ['Scientist', 'Philosopher', 'Software Developer', 'Engineer', 'Mathematician', 'Writer'],
  },
  entj: {
    code: 'ENTJ',
    name: 'The Commander',
    stack: 'Te-Ni-Se-Fi',
    description: 'Bold, strategic leaders who mobilize resources and people toward ambitious goals. Natural executives who create order from chaos.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Te', description: 'Extraverted Thinking organizes and executes efficiently' },
      { position: 'Auxiliary', function: 'Ni', description: 'Introverted Intuition provides strategic vision' },
      { position: 'Tertiary', function: 'Se', description: 'Extraverted Sensing engages with immediate reality' },
      { position: 'Inferior', function: 'Fi', description: 'Introverted Feeling connects to personal values' },
    ],
    keywords: ['decisive', 'ambitious', 'strategic', 'efficient', 'commanding'],
    strengths: ['Leadership', 'Strategic planning', 'Efficiency', 'Confidence', 'Organization'],
    challenges: ['May seem domineering', 'Impatience', 'Difficulty with emotions', 'Work-life balance'],
    famousExamples: ['Steve Jobs', 'Margaret Thatcher', 'Napoleon Bonaparte', 'Gordon Ramsay'],
    careers: ['Executive', 'Entrepreneur', 'Lawyer', 'Consultant', 'Manager', 'Politician'],
  },
  entp: {
    code: 'ENTP',
    name: 'The Debater',
    stack: 'Ne-Ti-Fe-Si',
    description: 'Quick-witted innovators who love intellectual challenges. They see possibilities everywhere and enjoy exploring ideas through debate.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ne', description: 'Extraverted Intuition generates possibilities and connections' },
      { position: 'Auxiliary', function: 'Ti', description: 'Introverted Thinking analyzes and refines ideas' },
      { position: 'Tertiary', function: 'Fe', description: 'Extraverted Feeling engages with social dynamics' },
      { position: 'Inferior', function: 'Si', description: 'Introverted Sensing grounds in past experience' },
    ],
    keywords: ['innovative', 'clever', 'entrepreneurial', 'resourceful', 'outspoken'],
    strengths: ['Innovation', 'Debate', 'Problem-solving', 'Adaptability', 'Big-picture thinking'],
    challenges: ['Follow-through', 'Routine tasks', 'Sensitivity to others', 'Argumentativeness'],
    famousExamples: ['Thomas Edison', 'Mark Twain', 'Leonardo da Vinci', 'Socrates'],
    careers: ['Entrepreneur', 'Lawyer', 'Consultant', 'Inventor', 'Marketing', 'Journalist'],
  },
  infj: {
    code: 'INFJ',
    name: 'The Advocate',
    stack: 'Ni-Fe-Ti-Se',
    description: 'Insightful idealists driven to help others. They combine deep intuition with genuine care for people to create meaningful change.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ni', description: 'Introverted Intuition provides deep insight and vision' },
      { position: 'Auxiliary', function: 'Fe', description: 'Extraverted Feeling connects with others\' needs' },
      { position: 'Tertiary', function: 'Ti', description: 'Introverted Thinking provides analytical framework' },
      { position: 'Inferior', function: 'Se', description: 'Extraverted Sensing engages with the physical world' },
    ],
    keywords: ['insightful', 'principled', 'compassionate', 'private', 'visionary'],
    strengths: ['Deep insight', 'Empathy', 'Dedication', 'Writing/creativity', 'Counseling'],
    challenges: ['Burnout', 'Perfectionism', 'Over-sensitivity', 'Difficulty with conflict'],
    famousExamples: ['Martin Luther King Jr.', 'Nelson Mandela', 'Carl Jung', 'Mother Teresa'],
    careers: ['Counselor', 'Writer', 'Psychologist', 'Teacher', 'Healthcare', 'Non-profit work'],
  },
  infp: {
    code: 'INFP',
    name: 'The Mediator',
    stack: 'Fi-Ne-Si-Te',
    description: 'Imaginative idealists guided by their own values and beliefs. They seek meaning and authenticity in everything they do.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Fi', description: 'Introverted Feeling guides deep personal values' },
      { position: 'Auxiliary', function: 'Ne', description: 'Extraverted Intuition explores possibilities' },
      { position: 'Tertiary', function: 'Si', description: 'Introverted Sensing connects to meaningful memories' },
      { position: 'Inferior', function: 'Te', description: 'Extraverted Thinking organizes and executes' },
    ],
    keywords: ['idealistic', 'creative', 'empathetic', 'authentic', 'reserved'],
    strengths: ['Creativity', 'Empathy', 'Writing', 'Deep thinking', 'Authenticity'],
    challenges: ['Practical matters', 'Criticism sensitivity', 'Self-isolation', 'Idealism vs reality'],
    famousExamples: ['William Shakespeare', 'J.R.R. Tolkien', 'Princess Diana', 'Edgar Allan Poe'],
    careers: ['Writer', 'Artist', 'Counselor', 'Psychologist', 'Teacher', 'Musician'],
  },
  enfj: {
    code: 'ENFJ',
    name: 'The Protagonist',
    stack: 'Fe-Ni-Se-Ti',
    description: 'Charismatic leaders who inspire others toward growth. They combine genuine care for people with a vision for what they can become.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Fe', description: 'Extraverted Feeling creates harmony and connection' },
      { position: 'Auxiliary', function: 'Ni', description: 'Introverted Intuition provides vision and insight' },
      { position: 'Tertiary', function: 'Se', description: 'Extraverted Sensing engages with the moment' },
      { position: 'Inferior', function: 'Ti', description: 'Introverted Thinking provides logical analysis' },
    ],
    keywords: ['charismatic', 'empathetic', 'inspiring', 'organized', 'diplomatic'],
    strengths: ['Leadership', 'Empathy', 'Communication', 'Inspiration', 'Organization'],
    challenges: ['Over-involvement', 'Approval-seeking', 'Neglecting own needs', 'Conflict avoidance'],
    famousExamples: ['Barack Obama', 'Oprah Winfrey', 'Martin Luther King Jr.', 'Abraham Lincoln'],
    careers: ['Teacher', 'Coach', 'Counselor', 'HR Manager', 'Public Relations', 'Politics'],
  },
  enfp: {
    code: 'ENFP',
    name: 'The Campaigner',
    stack: 'Ne-Fi-Te-Si',
    description: 'Enthusiastic, creative spirits who see life as full of possibilities. They inspire others with their energy and authenticity.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ne', description: 'Extraverted Intuition explores endless possibilities' },
      { position: 'Auxiliary', function: 'Fi', description: 'Introverted Feeling guides authentic values' },
      { position: 'Tertiary', function: 'Te', description: 'Extraverted Thinking helps execute ideas' },
      { position: 'Inferior', function: 'Si', description: 'Introverted Sensing grounds in experience' },
    ],
    keywords: ['enthusiastic', 'creative', 'sociable', 'optimistic', 'free-spirited'],
    strengths: ['Creativity', 'Enthusiasm', 'Communication', 'Empathy', 'Adaptability'],
    challenges: ['Focus', 'Follow-through', 'Overthinking', 'Practical details'],
    famousExamples: ['Robin Williams', 'Walt Disney', 'Mark Twain', 'Oscar Wilde'],
    careers: ['Writer', 'Actor', 'Counselor', 'Journalist', 'Marketing', 'Entrepreneur'],
  },
  istj: {
    code: 'ISTJ',
    name: 'The Logistician',
    stack: 'Si-Te-Fi-Ne',
    description: 'Responsible and thorough individuals who value tradition and reliability. They are the backbone of institutions.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Si', description: 'Introverted Sensing stores detailed experience' },
      { position: 'Auxiliary', function: 'Te', description: 'Extraverted Thinking organizes and executes' },
      { position: 'Tertiary', function: 'Fi', description: 'Introverted Feeling guides personal values' },
      { position: 'Inferior', function: 'Ne', description: 'Extraverted Intuition considers possibilities' },
    ],
    keywords: ['responsible', 'thorough', 'dependable', 'traditional', 'practical'],
    strengths: ['Reliability', 'Organization', 'Attention to detail', 'Commitment', 'Practical skills'],
    challenges: ['Rigidity', 'Change resistance', 'Emotional expression', 'Seeing alternatives'],
    famousExamples: ['George Washington', 'Queen Elizabeth II', 'Warren Buffett', 'Angela Merkel'],
    careers: ['Accountant', 'Lawyer', 'Military', 'Administrator', 'Engineer', 'Manager'],
  },
  isfj: {
    code: 'ISFJ',
    name: 'The Defender',
    stack: 'Si-Fe-Ti-Ne',
    description: 'Caring protectors who remember details about the people they care for. They quietly ensure others are looked after.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Si', description: 'Introverted Sensing recalls personal details' },
      { position: 'Auxiliary', function: 'Fe', description: 'Extraverted Feeling cares for others\' needs' },
      { position: 'Tertiary', function: 'Ti', description: 'Introverted Thinking provides logical analysis' },
      { position: 'Inferior', function: 'Ne', description: 'Extraverted Intuition explores possibilities' },
    ],
    keywords: ['supportive', 'reliable', 'patient', 'observant', 'loyal'],
    strengths: ['Reliability', 'Patience', 'Care for others', 'Memory', 'Practical support'],
    challenges: ['Overworking', 'Difficulty saying no', 'Change resistance', 'Neglecting self'],
    famousExamples: ['Mother Teresa', 'Queen Elizabeth II', 'Rosa Parks', 'Kate Middleton'],
    careers: ['Nurse', 'Teacher', 'Administrator', 'Social Worker', 'Librarian', 'Healthcare'],
  },
  estj: {
    code: 'ESTJ',
    name: 'The Executive',
    stack: 'Te-Si-Ne-Fi',
    description: 'Organized leaders who value order, tradition, and getting things done. They excel at managing people and processes.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Te', description: 'Extraverted Thinking organizes and directs' },
      { position: 'Auxiliary', function: 'Si', description: 'Introverted Sensing values proven methods' },
      { position: 'Tertiary', function: 'Ne', description: 'Extraverted Intuition considers alternatives' },
      { position: 'Inferior', function: 'Fi', description: 'Introverted Feeling connects to values' },
    ],
    keywords: ['organized', 'logical', 'assertive', 'practical', 'direct'],
    strengths: ['Organization', 'Leadership', 'Dedication', 'Reliability', 'Directness'],
    challenges: ['Inflexibility', 'Impatience', 'Emotional sensitivity', 'Work-life balance'],
    famousExamples: ['Henry Ford', 'Judge Judy', 'John D. Rockefeller', 'Lyndon B. Johnson'],
    careers: ['Manager', 'Administrator', 'Military', 'Lawyer', 'Business Owner', 'Judge'],
  },
  esfj: {
    code: 'ESFJ',
    name: 'The Consul',
    stack: 'Fe-Si-Ne-Ti',
    description: 'Warm, social connectors who create harmony in their communities. They remember personal details and care deeply about others.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Fe', description: 'Extraverted Feeling creates social harmony' },
      { position: 'Auxiliary', function: 'Si', description: 'Introverted Sensing remembers personal details' },
      { position: 'Tertiary', function: 'Ne', description: 'Extraverted Intuition considers possibilities' },
      { position: 'Inferior', function: 'Ti', description: 'Introverted Thinking provides logical analysis' },
    ],
    keywords: ['caring', 'sociable', 'traditional', 'loyal', 'organized'],
    strengths: ['Social skills', 'Loyalty', 'Practical care', 'Organization', 'Reliability'],
    challenges: ['Approval-seeking', 'Conflict sensitivity', 'Change resistance', 'Self-neglect'],
    famousExamples: ['Taylor Swift', 'Bill Clinton', 'Jennifer Garner', 'Sally Field'],
    careers: ['Teacher', 'Nurse', 'Administrator', 'Social Worker', 'Event Planner', 'Healthcare'],
  },
  istp: {
    code: 'ISTP',
    name: 'The Virtuoso',
    stack: 'Ti-Se-Ni-Fe',
    description: 'Cool-headed problem-solvers who excel with hands-on challenges. They understand how systems work and troubleshoot effectively.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Ti', description: 'Introverted Thinking analyzes how things work' },
      { position: 'Auxiliary', function: 'Se', description: 'Extraverted Sensing engages with physical reality' },
      { position: 'Tertiary', function: 'Ni', description: 'Introverted Intuition provides insight' },
      { position: 'Inferior', function: 'Fe', description: 'Extraverted Feeling navigates social situations' },
    ],
    keywords: ['practical', 'observant', 'analytical', 'reserved', 'adaptable'],
    strengths: ['Problem-solving', 'Crisis response', 'Technical skills', 'Adaptability', 'Calm under pressure'],
    challenges: ['Emotional expression', 'Long-term planning', 'Commitment', 'Social conventions'],
    famousExamples: ['Steve Jobs', 'Bruce Lee', 'Clint Eastwood', 'Michael Jordan'],
    careers: ['Engineer', 'Mechanic', 'Pilot', 'Surgeon', 'Forensics', 'Craftsperson'],
  },
  isfp: {
    code: 'ISFP',
    name: 'The Adventurer',
    stack: 'Fi-Se-Ni-Te',
    description: 'Gentle artists who live in the present and express themselves through action. They have strong values and aesthetic sense.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Fi', description: 'Introverted Feeling guides personal values' },
      { position: 'Auxiliary', function: 'Se', description: 'Extraverted Sensing engages with beauty and experience' },
      { position: 'Tertiary', function: 'Ni', description: 'Introverted Intuition provides insight' },
      { position: 'Inferior', function: 'Te', description: 'Extraverted Thinking organizes and executes' },
    ],
    keywords: ['artistic', 'sensitive', 'helpful', 'flexible', 'quiet'],
    strengths: ['Artistic expression', 'Sensitivity', 'Present-moment awareness', 'Loyalty', 'Aesthetic sense'],
    challenges: ['Long-term planning', 'Self-assertion', 'Dealing with conflict', 'Structure'],
    famousExamples: ['Bob Dylan', 'Rihanna', 'David Bowie', 'Frida Kahlo'],
    careers: ['Artist', 'Musician', 'Photographer', 'Chef', 'Veterinarian', 'Physical Therapist'],
  },
  estp: {
    code: 'ESTP',
    name: 'The Entrepreneur',
    stack: 'Se-Ti-Fe-Ni',
    description: 'Energetic risk-takers who thrive on action and live in the moment. They read situations quickly and act decisively.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Se', description: 'Extraverted Sensing engages with immediate reality' },
      { position: 'Auxiliary', function: 'Ti', description: 'Introverted Thinking analyzes and problem-solves' },
      { position: 'Tertiary', function: 'Fe', description: 'Extraverted Feeling reads social situations' },
      { position: 'Inferior', function: 'Ni', description: 'Introverted Intuition considers long-term implications' },
    ],
    keywords: ['energetic', 'perceptive', 'direct', 'rational', 'bold'],
    strengths: ['Quick thinking', 'Negotiation', 'Crisis response', 'Persuasion', 'Adaptability'],
    challenges: ['Long-term planning', 'Patience', 'Sensitivity to others', 'Following rules'],
    famousExamples: ['Donald Trump', 'Ernest Hemingway', 'Madonna', 'Bruce Willis'],
    careers: ['Entrepreneur', 'Sales', 'Paramedic', 'Sports', 'Marketing', 'Police'],
  },
  esfp: {
    code: 'ESFP',
    name: 'The Entertainer',
    stack: 'Se-Fi-Te-Ni',
    description: 'Spontaneous entertainers who bring joy and energy to every situation. They love people and new experiences.',
    cognitiveStack: [
      { position: 'Dominant', function: 'Se', description: 'Extraverted Sensing engages with the world' },
      { position: 'Auxiliary', function: 'Fi', description: 'Introverted Feeling guides personal values' },
      { position: 'Tertiary', function: 'Te', description: 'Extraverted Thinking helps with practical matters' },
      { position: 'Inferior', function: 'Ni', description: 'Introverted Intuition considers deeper meaning' },
    ],
    keywords: ['spontaneous', 'energetic', 'friendly', 'playful', 'practical'],
    strengths: ['Social skills', 'Optimism', 'Practical problem-solving', 'Adaptability', 'Present-focus'],
    challenges: ['Long-term planning', 'Focus', 'Serious topics', 'Delayed gratification'],
    famousExamples: ['Marilyn Monroe', 'Elvis Presley', 'Jamie Oliver', 'Adele'],
    careers: ['Entertainer', 'Sales', 'Teacher', 'Event Planner', 'Healthcare', 'Hospitality'],
  },
};

export const pageData = {
  '/': {
    title: 'TypeJung - Jungian Cognitive Function Assessment',
    description: 'Measure all 8 cognitive functions using the Singer-Loomis methodology. Discover your true psychological profile, not just 4 letters.',
  },
  '/assessment': {
    title: 'Take the Assessment | TypeJung',
    description: 'Start your free 40-question Jungian personality assessment. Measures all 8 cognitive functions independently. Takes 15-20 minutes.',
  },
  '/results': {
    title: 'Your Results | TypeJung',
    description: 'View your cognitive function assessment results with detailed radar chart and AI-powered insights.',
  },
  '/learn': {
    title: 'Learn Jungian Typology | TypeJung',
    description: 'Understand Carl Jung\'s theory of psychological types, the 8 cognitive functions, and how they shape personality.',
  },
  '/pricing': {
    title: 'Pricing Plans | TypeJung',
    description: 'Choose your TypeJung plan: Free ($0), Insight ($19), or Mastery ($39). Get deeper AI analysis, comprehensive reports, and AI coaching.',
  },
  '/privacy': {
    title: 'Privacy Policy | TypeJung',
    description: 'TypeJung\'s privacy policy explains how we collect, use, and protect your personal information.',
  },
  '/terms': {
    title: 'Terms of Service | TypeJung',
    description: 'Terms and conditions for using the TypeJung cognitive function assessment platform.',
  },
};
